language: python
python:
  - "2.7"
  - "3.5"
install:
  # Install required node version
  - "nvm install v6.9.1 && nvm use v6.9.1"
  # Install python deps. We start in base project directory
  - "cd python && pip install -r requirements.txt"
  # Install node deps
  - "cd ../node && npm install"
script:
  # python tests
  - "cd ../python && py.test"
  # node tests
  - "cd ../node && npm test"
